services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__AppDb: "Host=db;Port=5432;Database=monthspendingsdb;Username=postgres;Password=postgres"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monthspendingsdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: