//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked. Try again in {0} seconds..
        /// </summary>
        public static string AuthAccountLocked {
            get {
                return ResourceManager.GetString("AuthAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists..
        /// </summary>
        public static string AuthEmailExists {
            get {
                return ResourceManager.GetString("AuthEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string AuthInvalidCredentials {
            get {
                return ResourceManager.GetString("AuthInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Google credentials..
        /// </summary>
        public static string AuthInvalidGoogleCredentials {
            get {
                return ResourceManager.GetString("AuthInvalidGoogleCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string AuthPasswordTooShort {
            get {
                return ResourceManager.GetString("AuthPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter, one digit, and one special character..
        /// </summary>
        public static string AuthPasswordTooWeak {
            get {
                return ResourceManager.GetString("AuthPasswordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please log in again..
        /// </summary>
        public static string AuthRefreshTokenInvalid {
            get {
                return ResourceManager.GetString("AuthRefreshTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is no longer valid. Please log in again..
        /// </summary>
        public static string AuthRefreshTokenReused {
            get {
                return ResourceManager.GetString("AuthRefreshTokenReused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not a member of this budget..
        /// </summary>
        public static string BudgetMemberNotFound {
            get {
                return ResourceManager.GetString("BudgetMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active budget period found..
        /// </summary>
        public static string BudgetNoActivePeriod {
            get {
                return ResourceManager.GetString("BudgetNoActivePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget not found..
        /// </summary>
        public static string BudgetNotFound {
            get {
                return ResourceManager.GetString("BudgetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a member of this budget..
        /// </summary>
        public static string BudgetNotMember {
            get {
                return ResourceManager.GetString("BudgetNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the budget owner can remove members..
        /// </summary>
        public static string BudgetNotOwner {
            get {
                return ResourceManager.GetString("BudgetNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner cannot be removed from the budget..
        /// </summary>
        public static string BudgetOwnerCannotBeRemoved {
            get {
                return ResourceManager.GetString("BudgetOwnerCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner cannot leave the budget. Delete it instead..
        /// </summary>
        public static string BudgetOwnerCannotLeave {
            get {
                return ResourceManager.GetString("BudgetOwnerCannotLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro accounts are limited to {0} budgets..
        /// </summary>
        public static string BudgetProLimitReached {
            get {
                return ResourceManager.GetString("BudgetProLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To have more than one budget you must be a Pro..
        /// </summary>
        public static string BudgetProRequiredForMultiple {
            get {
                return ResourceManager.GetString("BudgetProRequiredForMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found..
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error has occurred..
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget invite not found..
        /// </summary>
        public static string InviteNotFound {
            get {
                return ResourceManager.GetString("InviteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This budget has reached the {0}-participant limit..
        /// </summary>
        public static string InviteParticipantLimitReached {
            get {
                return ResourceManager.GetString("InviteParticipantLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a Pro to join a budget with more than two participants..
        /// </summary>
        public static string InviteProRequiredForLargeBudget {
            get {
                return ResourceManager.GetString("InviteProRequiredForLargeBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email doesn&apos;t exist..
        /// </summary>
        public static string InviteUserNotFound {
            get {
                return ResourceManager.GetString("InviteUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} renamed category {1} to {2}..
        /// </summary>
        public static string PushCategoryRenamedBody {
            get {
                return ResourceManager.GetString("PushCategoryRenamedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category updated.
        /// </summary>
        public static string PushCategoryRenamedTitle {
            get {
                return ResourceManager.GetString("PushCategoryRenamedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added {1:0.00} {2} to {3}..
        /// </summary>
        public static string PushFundsAddedBody {
            get {
                return ResourceManager.GetString("PushFundsAddedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds added.
        /// </summary>
        public static string PushFundsAddedTitle {
            get {
                return ResourceManager.GetString("PushFundsAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} spent {1:0.00} {2} from {3}..
        /// </summary>
        public static string PushFundsSpentBody {
            get {
                return ResourceManager.GetString("PushFundsSpentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds spent.
        /// </summary>
        public static string PushFundsSpentTitle {
            get {
                return ResourceManager.GetString("PushFundsSpentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tavira to review your spending and stay on budget..
        /// </summary>
        public static string PushInactivityBody {
            get {
                return ResourceManager.GetString("PushInactivityBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We miss you!.
        /// </summary>
        public static string PushInactivityTitle {
            get {
                return ResourceManager.GetString("PushInactivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} accepted your budget invite!.
        /// </summary>
        public static string PushInviteAcceptedBody {
            get {
                return ResourceManager.GetString("PushInviteAcceptedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} declined your budget invite..
        /// </summary>
        public static string PushInviteDeclinedBody {
            get {
                return ResourceManager.GetString("PushInviteDeclinedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to a budget. Tap to see the invite..
        /// </summary>
        public static string PushInviteReceivedBody {
            get {
                return ResourceManager.GetString("PushInviteReceivedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget invite.
        /// </summary>
        public static string PushInviteReceivedTitle {
            get {
                return ResourceManager.GetString("PushInviteReceivedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget invite status.
        /// </summary>
        public static string PushInviteResponseTitle {
            get {
                return ResourceManager.GetString("PushInviteResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been removed from &quot;{0}&quot;..
        /// </summary>
        public static string PushKickedBody {
            get {
                return ResourceManager.GetString("PushKickedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from budget.
        /// </summary>
        public static string PushKickedTitle {
            get {
                return ResourceManager.GetString("PushKickedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted a spending of {1:0.00} {2} from {3}..
        /// </summary>
        public static string PushSpendingDeletedBody {
            get {
                return ResourceManager.GetString("PushSpendingDeletedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending deleted.
        /// </summary>
        public static string PushSpendingDeletedTitle {
            get {
                return ResourceManager.GetString("PushSpendingDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to spend more than the category balance..
        /// </summary>
        public static string SpendingInsufficientBalance {
            get {
                return ResourceManager.GetString("SpendingInsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending not found..
        /// </summary>
        public static string SpendingNotFound {
            get {
                return ResourceManager.GetString("SpendingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget not found or you don&apos;t have access..
        /// </summary>
        public static string StatisticsBudgetNotAccessible {
            get {
                return ResourceManager.GetString("StatisticsBudgetNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected periods do not belong to this budget..
        /// </summary>
        public static string StatisticsPeriodsMismatch {
            get {
                return ResourceManager.GetString("StatisticsPeriodsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature requires an active Pro subscription..
        /// </summary>
        public static string SubscriptionProRequired {
            get {
                return ResourceManager.GetString("SubscriptionProRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Please wait a minute and try again..
        /// </summary>
        public static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found..
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user. Please log in again..
        /// </summary>
        public static string UserInvalid {
            get {
                return ResourceManager.GetString("UserInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported language. Use en, bg or es..
        /// </summary>
        public static string UserUnsupportedLanguage {
            get {
                return ResourceManager.GetString("UserUnsupportedLanguage", resourceCulture);
            }
        }
    }
}
