// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520184741_AddUserActivityTracking")]
    partial class AddUserActivityTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppUserBudget", b =>
                {
                    b.Property<int>("BudgetsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("BudgetsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUserBudget");
                });

            modelBuilder.Entity("AppUserSavingsPot", b =>
                {
                    b.Property<int>("SavingsPotsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("SavingsPotsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUserSavingsPot");
                });

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GooglePhotoAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastInactivityNotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastVisited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Bank.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsentId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsentId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Domain.Bank.BankConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SyncStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BankConsent");
                });

            modelBuilder.Entity("Domain.Bank.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Categorized")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MerchantCode")
                        .HasColumnType("text");

                    b.Property<int?>("SpendingId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("SpendingId")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("Domain.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Domain.BudgetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("Domain.BudgetInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now()) + INTERVAL '2 days'");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("BudgetInvites");
                });

            modelBuilder.Entity("Domain.BudgetPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetPeriods");
                });

            modelBuilder.Entity("Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            Name = "US Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EUR",
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 3,
                            Code = "GBP",
                            Name = "British Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 4,
                            Code = "JPY",
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CAD",
                            Name = "Canadian Dollar",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AUD",
                            Name = "Australian Dollar",
                            Symbol = "A$"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CHF",
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CNY",
                            Name = "Chinese Yuan Renminbi",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 9,
                            Code = "SEK",
                            Name = "Swedish Krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 10,
                            Code = "NOK",
                            Name = "Norwegian Krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 11,
                            Code = "DKK",
                            Name = "Danish Krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 12,
                            Code = "NZD",
                            Name = "New Zealand Dollar",
                            Symbol = "NZ$"
                        },
                        new
                        {
                            Id = 13,
                            Code = "SGD",
                            Name = "Singapore Dollar",
                            Symbol = "S$"
                        },
                        new
                        {
                            Id = 14,
                            Code = "HKD",
                            Name = "Hong Kong Dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            Id = 15,
                            Code = "KRW",
                            Name = "South Korean Won",
                            Symbol = "₩"
                        },
                        new
                        {
                            Id = 16,
                            Code = "INR",
                            Name = "Indian Rupee",
                            Symbol = "₹"
                        },
                        new
                        {
                            Id = 17,
                            Code = "MXN",
                            Name = "Mexican Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BRL",
                            Name = "Brazilian Real",
                            Symbol = "R$"
                        },
                        new
                        {
                            Id = 19,
                            Code = "RUB",
                            Name = "Russian Ruble",
                            Symbol = "₽"
                        },
                        new
                        {
                            Id = 20,
                            Code = "ZAR",
                            Name = "South African Rand",
                            Symbol = "R"
                        },
                        new
                        {
                            Id = 21,
                            Code = "TRY",
                            Name = "Turkish Lira",
                            Symbol = "₺"
                        },
                        new
                        {
                            Id = 22,
                            Code = "AED",
                            Name = "UAE Dirham",
                            Symbol = "د.إ"
                        },
                        new
                        {
                            Id = 23,
                            Code = "PLN",
                            Name = "Polish Zloty",
                            Symbol = "zł"
                        },
                        new
                        {
                            Id = 24,
                            Code = "THB",
                            Name = "Thai Baht",
                            Symbol = "฿"
                        },
                        new
                        {
                            Id = 25,
                            Code = "IDR",
                            Name = "Indonesian Rupiah",
                            Symbol = "Rp"
                        },
                        new
                        {
                            Id = 26,
                            Code = "MYR",
                            Name = "Malaysian Ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            Id = 27,
                            Code = "PHP",
                            Name = "Philippine Peso",
                            Symbol = "₱"
                        },
                        new
                        {
                            Id = 28,
                            Code = "HUF",
                            Name = "Hungarian Forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            Id = 29,
                            Code = "CZK",
                            Name = "Czech Koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            Id = 30,
                            Code = "ILS",
                            Name = "Israeli Shekel",
                            Symbol = "₪"
                        },
                        new
                        {
                            Id = 31,
                            Code = "CLP",
                            Name = "Chilean Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 32,
                            Code = "PKR",
                            Name = "Pakistani Rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            Id = 33,
                            Code = "EGP",
                            Name = "Egyptian Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 34,
                            Code = "SAR",
                            Name = "Saudi Riyal",
                            Symbol = "﷼"
                        },
                        new
                        {
                            Id = 35,
                            Code = "COP",
                            Name = "Colombian Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 36,
                            Code = "VND",
                            Name = "Vietnamese Dong",
                            Symbol = "₫"
                        },
                        new
                        {
                            Id = 37,
                            Code = "BDT",
                            Name = "Bangladeshi Taka",
                            Symbol = "৳"
                        },
                        new
                        {
                            Id = 38,
                            Code = "NGN",
                            Name = "Nigerian Naira",
                            Symbol = "₦"
                        },
                        new
                        {
                            Id = 39,
                            Code = "KWD",
                            Name = "Kuwaiti Dinar",
                            Symbol = "د.ك"
                        },
                        new
                        {
                            Id = 40,
                            Code = "QAR",
                            Name = "Qatari Riyal",
                            Symbol = "﷼"
                        },
                        new
                        {
                            Id = 41,
                            Code = "OMR",
                            Name = "Omani Rial",
                            Symbol = "﷼"
                        },
                        new
                        {
                            Id = 42,
                            Code = "TWD",
                            Name = "New Taiwan Dollar",
                            Symbol = "NT$"
                        },
                        new
                        {
                            Id = 43,
                            Code = "ARS",
                            Name = "Argentine Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 44,
                            Code = "UAH",
                            Name = "Ukrainian Hryvnia",
                            Symbol = "₴"
                        });
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConnectionDbId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConnectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("ConnectionId");

                    b.ToTable("SaltEdgeAccounts");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorClass")
                        .HasColumnType("text");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("LastStage")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("LocalSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SaltEdgeCustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SyncStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.HasIndex("LocalSessionId")
                        .IsUnique();

                    b.HasIndex("SaltEdgeCustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("SaltEdgeConnections");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SaltEdgeCustomers");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Categorized")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MerchantCode")
                        .HasColumnType("text");

                    b.Property<int>("SaltEdgeAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpendingId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SaltEdgeAccountId");

                    b.HasIndex("SpendingId")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("SaltEdgeTransactions");
                });

            modelBuilder.Entity("Domain.SavingsContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("SavingsPotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("SavingsPotId");

                    b.ToTable("SavingsContributions");
                });

            modelBuilder.Entity("Domain.SavingsPot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("SavingsPots");
                });

            modelBuilder.Entity("Domain.SavingsPotInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SavingsPotId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now()) + INTERVAL '2 days'");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SavingsPotId");

                    b.HasIndex("SenderId");

                    b.ToTable("SavingsPotInvites");
                });

            modelBuilder.Entity("Domain.Spending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("BankTransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetPeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCategoryId");

                    b.HasIndex("BudgetPeriodId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Spendings");
                });

            modelBuilder.Entity("AppUserBudget", b =>
                {
                    b.HasOne("Domain.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUserSavingsPot", b =>
                {
                    b.HasOne("Domain.SavingsPot", null)
                        .WithMany()
                        .HasForeignKey("SavingsPotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Bank.BankAccount", b =>
                {
                    b.HasOne("Domain.Bank.BankConsent", "Consent")
                        .WithMany("Accounts")
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consent");
                });

            modelBuilder.Entity("Domain.Bank.BankConsent", b =>
                {
                    b.HasOne("Domain.AppUser", "User")
                        .WithMany("BankConsents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Bank.BankTransaction", b =>
                {
                    b.HasOne("Domain.Bank.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Spending", "Spending")
                        .WithOne("BankTransaction")
                        .HasForeignKey("Domain.Bank.BankTransaction", "SpendingId");

                    b.Navigation("BankAccount");

                    b.Navigation("Spending");
                });

            modelBuilder.Entity("Domain.Budget", b =>
                {
                    b.HasOne("Domain.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Domain.BudgetCategory", b =>
                {
                    b.HasOne("Domain.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Domain.BudgetInvite", b =>
                {
                    b.HasOne("Domain.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", "Receiver")
                        .WithMany("ReceivedBudgetInvites")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", "Sender")
                        .WithMany("SentBudgetInvites")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.BudgetPeriod", b =>
                {
                    b.HasOne("Domain.Budget", "Budget")
                        .WithMany("BudgetPeriods")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeAccount", b =>
                {
                    b.HasOne("Domain.SaltEdge.SaltEdgeConnection", "Connection")
                        .WithMany("Accounts")
                        .HasForeignKey("ConnectionId");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeConnection", b =>
                {
                    b.HasOne("Domain.SaltEdge.SaltEdgeCustomer", "Customer")
                        .WithMany("Connections")
                        .HasForeignKey("SaltEdgeCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeCustomer", b =>
                {
                    b.HasOne("Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeTransaction", b =>
                {
                    b.HasOne("Domain.SaltEdge.SaltEdgeAccount", "SaltEdgeAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("SaltEdgeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Spending", "Spending")
                        .WithOne()
                        .HasForeignKey("Domain.SaltEdge.SaltEdgeTransaction", "SpendingId");

                    b.Navigation("SaltEdgeAccount");

                    b.Navigation("Spending");
                });

            modelBuilder.Entity("Domain.SavingsContribution", b =>
                {
                    b.HasOne("Domain.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.SavingsPot", "SavingsPot")
                        .WithMany("Contributions")
                        .HasForeignKey("SavingsPotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("SavingsPot");
                });

            modelBuilder.Entity("Domain.SavingsPot", b =>
                {
                    b.HasOne("Domain.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Domain.SavingsPotInvite", b =>
                {
                    b.HasOne("Domain.AppUser", "Receiver")
                        .WithMany("ReceivedSavingsPotInvites")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.SavingsPot", "SavingsPot")
                        .WithMany("Invites")
                        .HasForeignKey("SavingsPotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", "Sender")
                        .WithMany("SentSavingsPotInvites")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("SavingsPot");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Spending", b =>
                {
                    b.HasOne("Domain.BudgetCategory", "BudgetCategory")
                        .WithMany("Spendings")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.BudgetPeriod", "BudgetPeriod")
                        .WithMany()
                        .HasForeignKey("BudgetPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", "CreatedBy")
                        .WithMany("CreatedSpendings")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetCategory");

                    b.Navigation("BudgetPeriod");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Navigation("BankConsents");

                    b.Navigation("CreatedSpendings");

                    b.Navigation("ReceivedBudgetInvites");

                    b.Navigation("ReceivedSavingsPotInvites");

                    b.Navigation("SentBudgetInvites");

                    b.Navigation("SentSavingsPotInvites");
                });

            modelBuilder.Entity("Domain.Bank.BankConsent", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.Budget", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("BudgetPeriods");
                });

            modelBuilder.Entity("Domain.BudgetCategory", b =>
                {
                    b.Navigation("Spendings");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeConnection", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.SaltEdge.SaltEdgeCustomer", b =>
                {
                    b.Navigation("Connections");
                });

            modelBuilder.Entity("Domain.SavingsPot", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Invites");
                });

            modelBuilder.Entity("Domain.Spending", b =>
                {
                    b.Navigation("BankTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
